spring:
  profiles:
    active:
    - dev

server:
  servlet:
    context-path: /session-jwt-login
    
---

spring:
  config:
    activate:
      on-profile:
      - dev
      
server:
  port: 8080
  
logging:
  file:
    name: dev.log
    
---

spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8081
  
logging:
  file:
    name: prod.log